[package]
name = "cxutil"
version = "0.1.0"
authors = ["Greg V <greg@unrelenting.technology>"]
edition = "2018"

[dependencies]
libc = "0"
zbus            = { git = "https://gitlab.freedesktop.org/dbus/zbus.git" }
zbus_polkit     = { git = "https://gitlab.freedesktop.org/dbus/zbus.git" }
